name: Hello QA CI

on: [push]

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Say Hello
        run: echo "🔧 Hello QA Alchemist!"